# -*- coding: utf-8 -*-
"""Almost Certainly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

def solve():
    t = int(input())
    for _ in range(t):
        n = int(input())
        a = list(map(int, input().split()))
        b = list(map(int, input().split()))

        total = 0
        max_diff = 0
        res = []

        for i in range(n):
            diff = a[i] - b[i]
            total += diff
            if diff > max_diff:
                max_diff = diff
            res.append(total - max_diff)

        print(*res)

if __name__ == "__main__":
    solve()