# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

def split_digits(x):
    return [int(d) for d in str(x)]

def solve():
    t = int(input())
    for _ in range(t):
        n = int(input())
        a = list(map(int, input().split()))
        b = []
        for x in a:
            if x >= 10:
                b.extend(split_digits(x))
            else:
                b.append(x)
        # Check if b is non-decreasing
        possible = all(b[i] <= b[i+1] for i in range(len(b)-1))
        print("YES" if possible else "NO")