# -*- coding: utf-8 -*-
"""Bessie's Birthday Cake (Hard Version).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

t = int(input())
for _ in range(t):
    n, x, y = map(int, input().split())
    _ = input()  # skip the x chosen vertices, values are irrelevant
    m = x + min(y, n - x)
    ans = max(0, m - 2)
    print(ans)