# -*- coding: utf-8 -*-
"""Bessie and MEX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
import heapq

input = sys.stdin.readline

t = int(input())
for _ in range(t):
    n = int(input())
    a = list(map(int, input().split()))

    used = [False] * n
    p = [0] * n
    mex_heap = []

    for i in range(n):
        # The MEX we want at this step
        mex = 0
        while mex < n and used[mex]:
            mex += 1

        p[i] = mex - a[i]
        used[p[i]] = True

    print(*p)