# -*- coding: utf-8 -*-
"""Big Persimmon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

n = int(input())
w = list(map(int, input().split()))

alice = 0
bob = 0

l, r = 0, n - 1  # pointers to the smallest and largest pieces

# Alice starts first
turn_alice = True

while l <= r:
    if turn_alice:
        # Alice picks the largest piece available
        alice += w[r]
        r -= 1
    else:
        # Bob picks the largest piece available
        bob += w[r]
        r -= 1
    turn_alice = not turn_alice  # alternate turns

print(alice, bob)