# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    n, k, p = map(int, input().split())

    dp = [1] * (k + 1)  # arrays of length 1
    for length in range(2, n + 1):
        new_dp = [0] * (k + 1)
        prefix = 0
        for val in range(k + 1):
            prefix = (prefix + dp[val]) % p
            new_dp[val] = prefix
        dp = new_dp

    print(sum(dp) % p)