# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

t = int(input())
for _ in range(t):
    n, k = map(int, input().split())
    if k < n - 1:
        print(n)
    else:
        print(1)