# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    n, k = map(int, input().split())
    a = list(map(int, input().split()))

    first_half = a[:n]
    second_half = a[n:]

    # Count occurrences in second half
    from collections import defaultdict, deque
    pos = defaultdict(deque)
    for i, x in enumerate(second_half):
        pos[x].append(x)

    l = first_half[:2*k]
    r = []
    for x in l:
        r.append(pos[x].popleft())

    print(*l)
    print(*r)