# -*- coding: utf-8 -*-
"""Evidence Board.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

from collections import deque, defaultdict

n = int(input())
edges = []
adj = [[] for _ in range(n)]
for i in range(n-1):
    a, b, w = map(int, input().split())
    a -= 1; b -= 1
    edges.append((a, b, w))
    adj[a].append((b, i))
    adj[b].append((a, i))

stickers = [deque(map(int, input().split())) for _ in range(n)]

order = []
queue = deque(i for i in range(n) if len(stickers[i]) == 1)

while queue:
    u = queue.popleft()
    if not stickers[u]:
        continue
    for v, idx in adj[u]:
        if stickers[v]:
            if stickers[u][0] + stickers[v][0] != edges[idx][2]:
                print("No")
                exit()
            order.append(idx + 1)
            stickers[u].popleft()
            stickers[v].popleft()
            if len(stickers[v]) == 1:
                queue.append(v)
            break

if len(order) == n-1:
    print("Yes")
    print(*order)
else:
    print("No")