# -*- coding: utf-8 -*-
"""Farmer John's Favorite Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import math
import sys
input = sys.stdin.readline

# Read n and q
n, q = map(int, input().split())
a = list(map(int, input().split()))

# Compute initial sum of square roots
sum_sqrt = sum(math.sqrt(ai) for ai in a)

for _ in range(q):
    k, x = map(int, input().split())
    k -= 1  # convert to 0-indexed

    # Update the sum by removing old value and adding new value
    sum_sqrt -= math.sqrt(a[k])
    a[k] = x
    sum_sqrt += math.sqrt(a[k])

    # Print the floor of the sum
    print(int(sum_sqrt))