# -*- coding: utf-8 -*-
"""Farmer John's Challenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

t = int(input())
for _ in range(t):
    n, k = map(int, input().split())

    # Impossible case
    if k == n - 1:
        print(-1)
        continue

    # Construct array:
    # First n-k elements in descending order
    # Last k elements in ascending order
    res = list(range(n - k, 0, -1)) + list(range(n - k + 1, n + 1))
    print(*res)