# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

t = int(input())
for _ in range(t):
    n, q = map(int, input().split())
    parent = list(map(int, input().split()))
    b = list(map(int, input().split()))

    total_needed = sum(b)
    total_growth = 0
    total_harvest = 0

    ops = [tuple(map(int, input().split())) for _ in range(q)]

    for typ, x, v in ops:
        if typ == 1:
            total_growth += v
        else:
            total_harvest += v
        # Easy check: can we reach total_needed with growth
        if total_growth >= total_needed:
            print("YES")
        else:
            print("NO")