# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import math
import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    a, b, m = map(int, input().split())
    g = math.gcd(a, b)
    ans = m // g + 2
    print(ans)