# -*- coding: utf-8 -*-
"""Learning to Paint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import heapq

t = int(input())
for _ in range(t):
    n, k = map(int, input().split())
    a = [[0]*(n+1) for _ in range(n+1)]
    for i in range(1, n+1):
        row = list(map(int, input().split()))
        for j, val in enumerate(row):
            a[i][i+j] = val

    dp = [[0]]  # dp[0] = [0]

    for i in range(1, n+1):
        tmp = dp[i-1][:]  # not paint i
        for j in range(1, i+1):
            for val in dp[j-1]:
                tmp.append(val + a[j][i])
        # Keep top k values
        dp_i = heapq.nlargest(k, tmp)
        dp.append(dp_i)

    print(*dp[n])