# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.read

def main():
    data = input().split()
    t = int(data[0])
    idx = 1
    results = []

    for _ in range(t):
        n = int(data[idx])
        idx += 1
        a = list(map(int, data[idx:idx+n]))
        idx += n

        a.sort()
        median_idx = n // 2  # 0-based index
        median_val = a[median_idx]

        # Minimum operations = sum of differences needed to increase median
        # We can increase all elements from median_idx to end
        operations = 0
        for i in range(median_idx, n):
            operations += a[i] - median_val

        # At least one operation is needed to increase median
        results.append(str(operations + 1))

    print("\n".join(results))

if __name__ == "__main__":
    main()