# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

from collections import Counter

t = int(input())
for _ in range(t):
    n = int(input())
    a = list(map(int, input().split()))

    freq = Counter(a)
    mex = 0

    while True:
        if freq[mex] >= 2:
            freq[mex] -= 2
            mex += 1
        elif freq[mex] == 1:
            freq[mex] -= 1
            mex += 1
        else:
            break
    print(mex)