# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    m, k = map(int, input().split())
    f = list(map(int, input().split()))

    mex = 0
    while mex <= m:
        if f[mex] % (k+1) == 0:
            mex += 1
        else:
            break
    print(mex)