# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    n = int(input())
    s = input().strip()
    t_str = input().strip()

    ans = 0
    i = 0
    while i < n:
        # identify a block of same characters in s
        j = i
        while j < n and s[j] == s[i]:
            j += 1
        # block is s[i:j]
        # calculate Hamming cost if block is all 0 or all 1
        cost0 = sum(1 for k in range(i, j) if t_str[k] != '0')
        cost1 = sum(1 for k in range(i, j) if t_str[k] != '1')
        ans += min(cost0, cost1)
        i = j
    print(ans)