# -*- coding: utf-8 -*-
"""More Gifts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

from collections import defaultdict

n, k, t = map(int, input().split())
gifts = list(map(int, input().split()))

# Count how many participants we need for **one stack**
participants = 1
current_types = defaultdict(int)
distinct_count = 0

for gift in gifts:
    if current_types[gift] == 0:
        distinct_count += 1
    current_types[gift] += 1

    if distinct_count > t:
        # Start new participant
        participants += 1
        current_types = defaultdict(int)
        current_types[gift] = 1
        distinct_count = 1

# Total participants considering k identical stacks
total_participants = participants * k
print(total_participants)