# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    n, q = map(int, input().split())
    s = input().strip()

    # Precompute differences between consecutive chars
    diff = [0]*(n)
    for i in range(1, n):
        diff[i] = diff[i-1] + (s[i] != s[i-1])

    for _ in range(q):
        l, r = map(int, input().split())
        l -= 1
        r -= 1
        if diff[r] - diff[l] == 0:  # all characters same
            print(0)
        else:
            length = r - l + 1
            print(length*(length+1)//2 - 1)