# -*- coding: utf-8 -*-
"""Rudolf and the Ugly String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

def solve():
    t = int(input())
    for _ in range(t):
        n = int(input())
        s = input().strip()
        i = 0
        deletions = 0
        while i <= n - 3:
            if s[i:i+3] == 'pie' or s[i:i+3] == 'map':
                deletions += 1
                i += 3  # skip the broken substring
            else:
                i += 1
        print(deletions)

if __name__ == "__main__":
    solve()