# -*- coding: utf-8 -*-
"""Rudolf and the Ticket.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

def solve():
    t = int(input())
    for _ in range(t):
        n, m, k = map(int, input().split())
        b = list(map(int, input().split()))
        c = list(map(int, input().split()))

        count = 0
        for bi in b:
            for ci in c:
                if bi + ci <= k:
                    count += 1
        print(count)

if __name__ == "__main__":
    solve()