# -*- coding: utf-8 -*-
"""Rudolf and Subway.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

from collections import defaultdict, deque
import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    n, m = map(int, input().split())
    edges_by_color = defaultdict(list)
    stations_on_color = defaultdict(list)

    graph = [[] for _ in range(n+1)]
    colors = defaultdict(list)

    for _ in range(m):
        u, v, c = map(int, input().split())
        colors[u].append((v,c))
        colors[v].append((u,c))

    b, e = map(int, input().split())

    # BFS: (station, color) -> min lines
    from heapq import heappush, heappop

    INF = int(1e9)
    dist = [INF]*(n+1)
    dist[b] = 0
    dq = deque()
    dq.append(b)

    while dq:
        u = dq.popleft()
        for v,c in colors[u]:
            if dist[v] > dist[u] + 1:
                dist[v] = dist[u] + 1
                dq.append(v)

    print(dist[e]-1)