# -*- coding: utf-8 -*-
"""Rudolf and 121.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

import sys
input = sys.stdin.readline

def solve():
    t = int(input())
    for _ in range(t):
        n = int(input())
        a = list(map(int, input().split()))
        possible = True

        for i in range(1, n-1):
            times = a[i] // 2
            a[i-1] -= times
            a[i]   -= 2 * times
            a[i+1] -= times
            if a[i-1] < 0 or a[i+1] < 0:
                possible = False
                break

        if possible and all(x == 0 for x in a):
            print("YES")
        else:
            print("NO")

if __name__ == "__main__":
    solve()