# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

def solve():
    t = int(input())
    for _ in range(t):
        n = int(input())
        if n == 1:
            print("NO")
            continue

        print("YES")
        s = ""
        full_blocks = n // 2
        s += "AA" * full_blocks
        if n % 2 == 1:
            s += "B"  # add one extra to reach odd n

        print(s)