# -*- coding: utf-8 -*-
"""Symmetric Boundary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FmJjMANIsqclTmTHPTG__5vjKBA9Jvon
"""

def midpoint(p1, p2):
    return ((p1[0]+p2[0])/2, (p1[1]+p2[1])/2)

def polygon_area(points):
    n = len(points)
    area = 0
    for i in range(n):
        x1, y1 = points[i]
        x2, y2 = points[(i+1)%n]
        area += x1*y2 - x2*y1
    return abs(area)/2

def main():
    import sys
    input = sys.stdin.readline
    n = int(input())
    points = [tuple(map(int, input().split())) for _ in range(n)]

    if n%2 != 0:
        print(-1)
        return

    k = n//2
    mid = midpoint(points[0], points[k])
    for i in range(1, k):
        if midpoint(points[i], points[i+k]) != mid:
            print(-1)
            return

    area = polygon_area(points)
    print(area)

if __name__ == "__main__":
    main()