# -*- coding: utf-8 -*-
"""Three Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBViAfENgDcfDNAsMmCgHg6iejhs2Eve
"""

def three_arrays():
    import sys
    input = sys.stdin.readline

    n = int(input())
    D = list(map(int, input().split()))
    L = list(map(int, input().split()))
    R = list(map(int, input().split()))
    a0, b0 = map(int, input().split())

    A = a0
    B = b0

    for i in range(n):
        # Calculate options if we pick A[i] = min(...)
        newA = min(A + D[i], L[i])
        newB = B + D[i]
        option1 = (newA, newB)

        # Calculate options if we pick B[i] = min(...)
        newA2 = A + D[i]
        newB2 = min(B + D[i], R[i])
        option2 = (newA2, newB2)

        # Choose the option giving maximum sum
        if option1[0] + option1[1] >= option2[0] + option2[1]:
            A, B = option1
        else:
            A, B = option2

    print(A + B)

if __name__ == "__main__":
    three_arrays()